### ISSUE TITLE
Missing newer OS versions

### ISSUE THREAD

**Issue by rcdailey** [pruggitorg/detect-windows-version#14]
The OperatingSystem enum is missing a few:

- Windows 11
- Windows Server 2022
- Windows Server 2019

**Comment by pruggit** [comment]
Currently there is no official way provided by Microsoft, which allows to determine Windows 11 by using the version numbers. According to the [Operating System Version](https://docs.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version)  documentation, Windows 11 and Windows 10 (and Windows Server 2016 through Windows Server 2022) are having the same version number 10.0. It seems, that for Microsoft it is more like a "platform version".

It might be because e.g. Windows 11 is just a marketing name and uses the basic system architecture of Windows 10. 

As far as I know, the distinction can currently only be made based on the build number, where e.g Windows 11 has a number with 22000 or higher.

Nevertheless, the enums need an update regarding the Windows product names.

- [ ] add OS detection strategy to readme file
- [ ] define a method to reflect current and future Windows product names in the enums

**Comment by rcdailey** [comment]
Here is how I reasoned about the version numbers on my side. Granted some of this may be inaccurate or unreliable, but it seems to work in the testing I did.

```cs
public static OsVersionEnum GetVersionEnum()
{
    var ver = (OSVersion.MajorVersion, OSVersion.BuildNumber, OSVersion.IsServer);
    return ver switch
    {
        (< 10, _, false) => OsVersionEnum.PreWin10,
        (< 10, _, true) => OsVersionEnum.PreWin2019,
        (10, >= 22000, false) => OsVersionEnum.Win11,
        (10, < 22000, false) => OsVersionEnum.Win10,
        (10, >= 20000, true) => OsVersionEnum.Win2022,
        (10, >= 17763, true) => OsVersionEnum.Win2019,
        _ => OsVersionEnum.Unknown
    };
}
```

**Comment by daluu** [comment]
This may be useful reference as well that I came across before: https://www.dell.com/support/kbdoc/en-gy/000193571/windows-11-incorrect-os-version-reported.

**Comment by pruggit** [comment]
Here is an interesting discussion that shows what developers or administrators would like to have regarding versioning and what Microsoft thinks about it.

https://learn.microsoft.com/en-us/answers/questions/586619/windows-11-build-ver-is-still-10022000194.html?page=2&pageSize=10&sort=oldest

**Comment by DirectInput** [comment]
Hi, I wanted to see if this was still being worked ?  Thanks

**Comment by pruggit** [comment]
Support for Windows 11 and Server 2022 have been added. #21
